In [62]:
import cv2 as cv
import numpy as np

In [63]:
img = cv.imread('Apple.jpeg')

In [64]:
cv.imshow('a', img)
cv.waitKey(0)
# cv.destroyAllWindows()

-1

In [65]:
blank = np.zeros((500,500,3), dtype='uint8')

Try painting the image a certain color

In [66]:
cv.rectangle(blank, (0,0), (250,250), (0,250,0), thickness=-1)

array([[[  0, 250,   0],
        [  0, 250,   0],
        [  0, 250,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0, 250,   0],
        [  0, 250,   0],
        [  0, 250,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0, 250,   0],
        [  0, 250,   0],
        [  0, 250,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [67]:
img = cv.imshow('Rectangle',blank)
cv.waitKey(5000)
cv.destroyAllWindows()

In [68]:
cv.circle(blank, (250,250), 100, (50, 60, 255), thickness = 4 )

array([[[  0, 250,   0],
        [  0, 250,   0],
        [  0, 250,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0, 250,   0],
        [  0, 250,   0],
        [  0, 250,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0, 250,   0],
        [  0, 250,   0],
        [  0, 250,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [69]:
cv.imshow('Circle', blank)
cv.waitKey(5000)
cv.destroyAllWindows()

Draw a line

In [74]:
cv.line(blank,(400,400), (400,200), (255,0,0), thickness = 4 )

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [75]:
cv.imshow('w a line', blank)
cv.waitKey(2000)
cv.destroyAllWindows()

Write text on an image

In [90]:
blank = np.zeros((500,500), dtype='uint8')

In [91]:
cv.putText(blank, 'Hello', (250,250), cv.FONT_HERSHEY_TRIPLEX, 1.00, color = (250,0,0), thickness = 2)
cv.imshow('Hello', blank)
cv.waitKey(2000)
cv.destroyAllWindows()